version: "3"

services:
  aip_food_lookup:
    image: aip_food_lookup:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: ${AIP_FOOD_LOOKUP_HOST}.com
      LETSENCRYPT_HOST: ${AIP_FOOD_LOOKUP_HOST}.com
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    container_name: aip_food_lookup
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy


