version: "3"

services:
  aip_food_lookup:
    image: aip_food_lookup:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: api.hashimojoe.com.com
      LETSENCRYPT_HOST: api.hashimojoe.com.com
      LETSENCRYPT_EMAIL: calypsosystemsllc@gmail.com
    container_name: aip_food_lookup
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy


