version: "3"

services:
  aip_food_lookup:
    image: aip_food_lookup:latest
    expose:
      - 8080
    restart: always
    volumes:
      - ./data:/var/log/data
    environment:
      AIP_DATA_FOLDER: /var/log/data
      VIRTUAL_HOST: api.hashimojoe.com
      LETSENCRYPT_HOST: api.hashimojoe.com
      LETSENCRYPT_EMAIL: calypsosystemsllc@gmail.com
    container_name: aip_food_lookup
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy


